In [ ]:
# import python libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt # visualizing data
%matplotlib inline
import seaborn as sns

In [ ]:
# import csv file
df = pd.read_csv ('/content/Ecommerce Purchases')

In [ ]:
df

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04
4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,es,77.82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,"966 Castaneda Locks\nWest Juliafurt, CO 96415",92 XI,PM,Mozilla/5.0 (Windows NT 5.1) AppleWebKit/5352 ...,Randall-Sloan,342945015358701,03/22,838,JCB 15 digit,iscott@wade-garner.com,Printmaker,29.73.197.114,it,82.21
9996,"832 Curtis Dam Suite 785\nNorth Edwardburgh, T...",41 JY,AM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Hale, Collins and Wilson",210033169205009,07/25,207,JCB 16 digit,mary85@hotmail.com,Energy engineer,121.133.168.51,pt,25.63
9997,Unit 4434 Box 6343\nDPO AE 28026-0283,74 Zh,AM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Anderson Ltd,6011539787356311,05/21,1,VISA 16 digit,tyler16@gmail.com,Veterinary surgeon,156.210.0.254,el,83.98
9998,"0096 English Rest\nRoystad, IA 12457",74 cL,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_8;...,Cook Inc,180003348082930,11/17,987,American Express,elizabethmoore@reid.net,Local government officer,55.78.26.143,es,38.84
9999,"40674 Barrett Stravenue\nGrimesville, WI 79682",64 Hr,AM,Mozilla/5.0 (X11; Linux i686; rv:1.9.5.20) Gec...,Greene Inc,4139972901927273,02/19,302,JCB 15 digit,rachelford@vaughn.com,"Embryologist, clinical",176.119.198.199,el,67.59

In [ ]:
#Display Top 10 Rows of The Dataset
df.head(10)

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04
4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,es,77.82
5,"7502 Powell Mission Apt. 768\nTravisland, VA 3...",21 XT,PM,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_8_5...,Silva-Anderson,30246185196287,07/25,7169,Discover,ynguyen@gmail.com,Fish farm manager,55.96.152.147,ru,25.15
6,"93971 Conway Causeway\nAndersonburgh, AZ 75107",96 Xt,AM,Mozilla/5.0 (compatible; MSIE 7.0; Windows NT ...,Gibson and Sons,6011398782655569,07/24,714,VISA 16 digit,olivia04@yahoo.com,Dancer,127.252.144.18,de,88.56
7,"260 Rachel Plains Suite 366\nCastroberg, WV 24...",96 pG,PM,Mozilla/5.0 (X11; Linux i686) AppleWebKit/5350...,Marshall-Collins,561252141909,06/25,256,VISA 13 digit,phillip48@parks.info,Event organiser,224.247.97.150,pt,44.25
8,"2129 Dylan Burg\nNew Michelle, ME 28650",45 JN,PM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Galloway and Sons,180041795790001,04/24,899,JCB 16 digit,kdavis@rasmussen.com,Financial manager,146.234.201.229,ru,59.54
9,"3795 Dawson Extensions\nLake Tinafort, ID 88739",15 Ug,AM,Mozilla/5.0 (X11; Linux i686; rv:1.9.7.20) Gec...,"Rivera, Buchanan and Ramirez",4396283918371,01/17,931,American Express,qcoleman@hunt-huerta.com,Forensic scientist,236.198.199.8,zh,95.63

In [ ]:
#Check Last 10 Rows of The Dataset
df.tail(10)

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
9990,"75731 Molly Springs\nWest Danielle, VT 96934-5102",93 ty,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_4;...,"Pace, Vazquez and Richards",869968197049750,04/24,877,JCB 15 digit,andersonmichael@sherman.biz,Early years teacher,54.170.3.185,ru,18.35
9991,"PSC 8165, Box 8498\nAPO AP 60327-0346",50 dA,AM,Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...,Snyder Inc,4221582137197481,02/24,969,Voyager,kking@wise-liu.com,IT sales professional,254.25.31.156,el,25.93
9992,"885 Allen Mountains Apt. 230\nWallhaven, LA 16995",40 vH,PM,Mozilla/5.0 (Macintosh; PPC Mac OS X 10_6_5) A...,Wells Ltd,4664825258997302,10/20,431,Discover,bberry@wright.net,Set designer,174.173.51.32,de,67.96
9993,"7555 Larson Locks Suite 229\nEllisburgh, MA 34...",72 jg,PM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_8...,Colon and Sons,30025560104631,10/25,629,Maestro,chelseawilliams@lopez.biz,"Designer, exhibition/display",177.46.82.128,el,65.61
9994,"6276 Rojas Hollow\nLake Louis, WY 56410-7837",93 Ex,PM,Opera/9.68.(X11; Linux x86_64; sl-SI) Presto/2...,Ritter-Smith,3112186784121077,01/25,1823,Maestro,iroberts@gmail.com,"Education officer, museum",242.44.112.18,zh,31.85
9995,"966 Castaneda Locks\nWest Juliafurt, CO 96415",92 XI,PM,Mozilla/5.0 (Windows NT 5.1) AppleWebKit/5352 ...,Randall-Sloan,342945015358701,03/22,838,JCB 15 digit,iscott@wade-garner.com,Printmaker,29.73.197.114,it,82.21
9996,"832 Curtis Dam Suite 785\nNorth Edwardburgh, T...",41 JY,AM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Hale, Collins and Wilson",210033169205009,07/25,207,JCB 16 digit,mary85@hotmail.com,Energy engineer,121.133.168.51,pt,25.63
9997,Unit 4434 Box 6343\nDPO AE 28026-0283,74 Zh,AM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Anderson Ltd,6011539787356311,05/21,1,VISA 16 digit,tyler16@gmail.com,Veterinary surgeon,156.210.0.254,el,83.98
9998,"0096 English Rest\nRoystad, IA 12457",74 cL,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_8;...,Cook Inc,180003348082930,11/17,987,American Express,elizabethmoore@reid.net,Local government officer,55.78.26.143,es,38.84
9999,"40674 Barrett Stravenue\nGrimesville, WI 79682",64 Hr,AM,Mozilla/5.0 (X11; Linux i686; rv:1.9.5.20) Gec...,Greene Inc,4139972901927273,02/19,302,JCB 15 digit,rachelford@vaughn.com,"Embryologist, clinical",176.119.198.199,el,67.59

In [ ]:
#Check Datatype of Each Column
df.dtypes

Address              object
Lot                  object
AM or PM             object
Browser Info         object
Company              object
Credit Card           int64
CC Exp Date          object
CC Security Code      int64
CC Provider          object
Email                object
Job                  object
IP Address           object
Language             object
Purchase Price      float64
dtype: object

In [ ]:
#Check null values in the dataset
df.isnull()

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9996,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9997,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9998,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9999,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
#How many rows and columns are there in our Dataset?
len(df.columns)
len(df)

10000

In [ ]:
#Highest and Lowest Purchase Prices.
df["Purchase Price"]

0       98.14
1       70.73
2        0.95
3       78.04
4       77.82
        ...
9995    82.21
9996    25.63
9997    83.98
9998    38.84
9999    67.59
Name: Purchase Price, Length: 10000, dtype: float64

In [ ]:
df["Purchase Price"].max()

99.99

In [ ]:
df["Purchase Price"].min()

0.0

In [ ]:
#Average Purchase Price
df["Purchase Price"].mean()

50.347302

In [ ]:
#How many people have French 'fr' as their Language?
df.columns

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='object')

In [ ]:
df[df["Language"]=="fr"]

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
19,"125 Hall Summit\nBoothton, IL 41721",99 CU,PM,Mozilla/5.0 (compatible; MSIE 7.0; Windows NT ...,Turner-Mckinney,676343504830,02/20,440,VISA 16 digit,ruiznicole@gmail.com,"Designer, interior/spatial",25.105.209.214,fr,58.39
53,"PSC 9431, Box 7059\nAPO AA 29285-1363",14 qD,AM,Opera/9.34.(X11; Linux x86_64; it-IT) Presto/2...,"Higgins, Cardenas and Kennedy",869972604798355,08/17,157,JCB 16 digit,amorales@yahoo.com,Technical author,44.108.117.122,fr,10.41
76,"49206 Campbell Port\nNorth Cliffordshire, HI 3...",71 iu,PM,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_5_9...,Jacobs-Tucker,6011343518820988,01/17,806,Voyager,eperez@hotmail.com,Paramedic,210.207.58.168,fr,57.34
82,493 Smith Valleys Suite 004\nNew Madelineville...,35 ls,PM,Mozilla/5.0 (iPod; U; CPU iPhone OS 4_0 like M...,"Robinson, Johnston and Valdez",4351359627548412,06/17,937,VISA 13 digit,amendez@yahoo.com,"Engineer, materials",163.129.163.100,fr,49.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9941,"43757 Brown Lodge\nValerieberg, PR 88518",68 DG,AM,Mozilla/5.0 (compatible; MSIE 5.0; Windows NT ...,"Jones, Williams and Dunn",6011508474487291,04/26,906,Mastercard,christian55@gmail.com,Secondary school teacher,216.118.235.145,fr,60.03
9947,"32827 Carl Inlet\nSouth Nicole, NY 38081-6636",40 Dp,PM,Mozilla/5.0 (Windows; U; Windows 95) AppleWebK...,Pruitt-Flores,3158564208754951,03/17,386,Mastercard,josephsmith@gmail.com,Textile designer,198.68.38.23,fr,49.61
9951,"518 Brown Dam\nGarciaside, IN 33057",71 wq,AM,Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...,"Crosby, Vasquez and Ballard",5256758441931287,12/17,146,VISA 16 digit,cjennings@yahoo.com,"Lighting technician, broadcasting/film/video",58.12.83.1,fr,57.59
9977,"02182 Keith Expressway\nEast Shannon, CT 20578...",34 RL,AM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Deleon, Jacobson and Benton",4186094003664688,06/21,397,JCB 16 digit,daltoncarter@yahoo.com,Biomedical engineer,146.238.118.2,fr,94.93
9980,"6061 Dave Lights\nPhillipsview, UT 40500",25 Mv,AM,Opera/8.58.(Windows NT 5.0; it-IT) Presto/2.9....,Cortez-Frye,6011944199756993,12/24,755,JCB 15 digit,mark74@kirby-stewart.org,Textile designer,110.103.77.195,fr,16.05

In [ ]:
#Job Title Contains Engineer
df[df["Job"].str.contains("Engineer",case=False)]

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04
50,"41159 Michael Centers\nAdamsfort, RI 37108-6674",46 Ce,PM,Mozilla/5.0 (Windows 98; Win 9x 4.90; sl-SI; r...,"Wright, Williams and Mendez",4008586485908075,05/19,945,JCB 16 digit,susanvalentine@obrien.org,Mechanical engineer,213.203.143.215,de,36.85
55,"27635 Maureen Bypass Apt. 883\nSandraview, SD ...",59 LJ,AM,Mozilla/5.0 (iPod; U; CPU iPhone OS 3_3 like M...,Sims-Lyons,3158113629128344,09/19,857,VISA 16 digit,adkinsarthur@yahoo.com,"Engineer, broadcasting (operations)",227.235.89.210,pt,48.74
60,"7126 Katherine Squares\nPerkinsview, CO 97299-...",63 qu,AM,Opera/8.68.(X11; Linux x86_64; en-US) Presto/2...,Marshall-Fernandez,349767747049645,05/20,672,JCB 15 digit,sweeneyhannah@jones.biz,"Engineer, agricultural",197.144.142.102,de,20.43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9948,"95544 Johnson Isle Suite 939\nMichaelberg, RI ...",91 bW,AM,Opera/8.36.(X11; Linux x86_64; sl-SI) Presto/2...,Fox-Peterson,4762924304307,03/17,567,Mastercard,haleybenjamin@gmail.com,Structural engineer,120.36.140.58,en,71.89
9952,"9991 Vaughn Hills\nRacheltown, PA 55409",36 KC,PM,Mozilla/5.0 (X11; Linux i686; rv:1.9.5.20) Gec...,"Ward, Smith and Castillo",6011679271321726,09/19,964,Voyager,jonesjennifer@olson.com,"Engineer, energy",116.228.12.42,es,39.63
9970,"0060 Keith Stream\nWestport, CO 47097",11 nt,PM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_8...,"Carpenter, Good and Hart",6011485664704662,07/19,543,Discover,rangelbrian@hotmail.com,Electrical engineer,242.8.85.205,en,17.76
9977,"02182 Keith Expressway\nEast Shannon, CT 20578...",34 RL,AM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Deleon, Jacobson and Benton",4186094003664688,06/21,397,JCB 16 digit,daltoncarter@yahoo.com,Biomedical engineer,146.238.118.2,fr,94.93
9996,"832 Curtis Dam Suite 785\nNorth Edwardburgh, T...",41 JY,AM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Hale, Collins and Wilson",210033169205009,07/25,207,JCB 16 digit,mary85@hotmail.com,Energy engineer,121.133.168.51,pt,25.63

In [ ]:
len(df[df["Job"].str.contains("Engineer",case=False)])

984

In [ ]:
#Find The Email of the person with the following IP Address: 132.207.160.22
df[df["IP Address"]==("132.207.160.22")]

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95

In [ ]:
df[df["IP Address"]==("132.207.160.22")]["Email"]

2    amymiller@morales-harrison.com
Name: Email, dtype: object

In [ ]:
#How many People have Mastercard as their Credit Card Provider and made a purchase above 50?
df["CC Provider"]

0                      JCB 16 digit
1                        Mastercard
2                      JCB 16 digit
3                          Discover
4       Diners Club / Carte Blanche
                   ...
9995                   JCB 15 digit
9996                   JCB 16 digit
9997                  VISA 16 digit
9998               American Express
9999                   JCB 15 digit
Name: CC Provider, Length: 10000, dtype: object

In [ ]:
df[(df["CC Provider"]=="Mastercard") & (df["Purchase Price"]>50)]

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
18,"461 Christopher Square\nWest Michaelchester, C...",17 SB,PM,Mozilla/5.0 (X11; Linux i686; rv:1.9.6.20) Gec...,"Beard, Abbott and Pena",6011350184276270,12/22,767,Mastercard,hannah63@yahoo.com,Photographer,73.250.176.201,el,70.15
31,USNS Alvarado\nFPO AA 27052-1231,26 Lh,PM,Opera/8.84.(X11; Linux i686; sl-SI) Presto/2.9...,Nicholson Group,4614997834548,03/22,909,Mastercard,ashley12@hotmail.com,Sales executive,94.176.142.201,en,94.14
35,"93392 Webb Gardens Apt. 220\nLaurabury, AR 999...",37 om,AM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Mora Ltd,6011049630969815,09/16,367,Mastercard,hgonzalez@mcdowell.com,"Lecturer, further education",216.23.95.40,zh,97.46
90,"431 Bowen Lights\nFergusonborough, MH 01362",31 tG,AM,Mozilla/5.0 (Windows NT 5.2; it-IT; rv:1.9.1.2...,Copeland-Lee,639032576097,06/18,868,Mastercard,nrogers@brown.com,"Teacher, English as a foreign language",153.188.13.203,es,78.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9941,"43757 Brown Lodge\nValerieberg, PR 88518",68 DG,AM,Mozilla/5.0 (compatible; MSIE 5.0; Windows NT ...,"Jones, Williams and Dunn",6011508474487291,04/26,906,Mastercard,christian55@gmail.com,Secondary school teacher,216.118.235.145,fr,60.03
9948,"95544 Johnson Isle Suite 939\nMichaelberg, RI ...",91 bW,AM,Opera/8.36.(X11; Linux x86_64; sl-SI) Presto/2...,Fox-Peterson,4762924304307,03/17,567,Mastercard,haleybenjamin@gmail.com,Structural engineer,120.36.140.58,en,71.89
9954,"051 Samantha Wells Apt. 328\nScottborough, OR ...",11 vG,AM,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_8_2...,"Mendoza, Zimmerman and Reilly",30232295374907,05/21,762,Mastercard,brownamy@perkins.com,"Presenter, broadcasting",61.97.84.101,it,87.15
9981,"087 Larson Roads Apt. 587\nRicestad, WI 98077-...",95 Kw,AM,Opera/9.63.(Windows NT 5.01; en-US) Presto/2.9...,"Ortiz, Schultz and Adams",4690863684605,01/19,695,Mastercard,laurenbennett@richards.com,Environmental education officer,106.21.237.73,pt,63.61
9987,"2754 Klein Mission\nJohnsonview, PA 64925-9624",65 Fg,PM,Opera/9.26.(Windows CE; sl-SI) Presto/2.9.188 ...,Curtis LLC,180027305702263,12/24,865,Mastercard,denisehamilton@novak.biz,Primary school teacher,164.39.190.217,es,60.83

In [ ]:
len(df[(df["CC Provider"]=="Mastercard") & (df["Purchase Price"]>50)])

405

In [ ]:
#Find the email of the person with the following Credit Card Number: 4664825258997302
df[df["Credit Card"]==4664825258997302]["Email"]

9992    bberry@wright.net
Name: Email, dtype: object

In [ ]:
#How many people purchase during the AM and how many people purchase during PM?
df["AM or PM"].value_counts()

PM    5068
AM    4932
Name: AM or PM, dtype: int64

In [ ]:
#How many people have a credit card that expires in 2020?
def fun():
  count=0
  for date in df("CC Exp Date"):
    if date.split("/")[1]=="20":
      count=count+1
    print(count)

In [ ]:
df[df["CC Exp Date"].apply(lambda x:x[3:]=="20")]

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
19,"125 Hall Summit\nBoothton, IL 41721",99 CU,PM,Mozilla/5.0 (compatible; MSIE 7.0; Windows NT ...,Turner-Mckinney,676343504830,02/20,440,VISA 16 digit,ruiznicole@gmail.com,"Designer, interior/spatial",25.105.209.214,fr,58.39
32,Unit 3628 Box 6778\nDPO AE 72362,39 Qm,PM,Mozilla/5.0 (Windows 98; Win 9x 4.90) AppleWeb...,Martinez-Wilson,4942281854569455,01/20,8360,JCB 16 digit,shane21@atkinson.com,Civil Service fast streamer,196.37.134.217,pt,56.63
36,"9374 Skinner Common Apt. 254\nChristopherfort,...",80 Fq,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,Hanna-Grant,180042289507877,09/20,912,VISA 16 digit,saundersernest@walsh.com,Animal technologist,85.134.58.250,zh,9.77
38,"9671 Riley Drives Apt. 746\nPort Davidtown, TN...",15 vj,AM,Mozilla/5.0 (X11; Linux i686; rv:1.9.6.20) Gec...,"Bryant, Hubbard and Gonzales",210094965373094,12/20,248,Voyager,djennings@boyd-english.org,Music therapist,143.138.65.219,en,30.07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9883,"751 Petersen Groves\nLake Rebecca, NM 55875",61 tE,PM,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_8_7...,Perez and Sons,4939814860063025,05/20,238,Mastercard,lisa25@hotmail.com,Therapeutic radiographer,215.85.159.70,pt,67.47
9901,"908 Norman Burgs\nPhillipsberg, VT 92023-9956",90 Ng,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,Hughes Inc,30148833294789,09/20,483,Voyager,james32@gmail.com,Meteorologist,250.66.85.29,en,57.25
9911,"44320 Gray Centers Suite 325\nJenniferfurt, OK...",19 Bf,PM,Mozilla/5.0 (X11; Linux i686; rv:1.9.7.20) Gec...,Jones-Gray,4058074716188,12/20,921,Diners Club / Carte Blanche,hensonlindsay@graves-fox.com,"Optician, dispensing",84.118.30.56,en,20.63
9957,"73556 Chase Pine\nBrucemouth, MP 73473",25 rU,PM,Opera/9.49.(Windows 95; en-US) Presto/2.9.189 ...,"Martin, Clayton and Jarvis",3337737293232646,05/20,798,VISA 13 digit,latashaochoa@gmail.com,Therapeutic radiographer,239.219.241.162,ru,71.85
9992,"885 Allen Mountains Apt. 230\nWallhaven, LA 16995",40 vH,PM,Mozilla/5.0 (Macintosh; PPC Mac OS X 10_6_5) A...,Wells Ltd,4664825258997302,10/20,431,Discover,bberry@wright.net,Set designer,174.173.51.32,de,67.96

In [ ]:
len(df[df["CC Exp Date"].apply(lambda x:x[3:]=="20")])

988

#Case Study on Employee Salary Data

In [1]:
import pandas as pd

In [2]:
df2=pd.read_csv("/content/Salaries.csv")

In [3]:

df2

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011.0,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011.0,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011.0,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011.0,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011.0,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
49725,49726,Crystal DeFrantz,Emp & Training Spec 4,84086.48,0.00,624.01,35661.88,84710.49,120372.37,2012.0,NaN,San Francisco,NaN
49726,49727,Antoinette Wells,Transit Operator,66714.31,13722.09,1549.20,38368.67,81985.60,120354.27,2012.0,NaN,San Francisco,NaN
49727,49728,Robert Rudy,Stationary Engineer,73814.00,15484.85,7035.40,24019.82,96334.25,120354.07,2012.0,NaN,San Francisco,NaN
49728,49729,Sean Kerrisk,Carpenter,78931.55,3516.76,2193.00,35710.67,84641.31,120351.98,2012.0,NaN,San Francisco,NaN
49729,49730,Rachelle Axel,Senior Management Assistant,8.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
#o perform data analysis, I have mentioned 21 questions that we are going to solve one by one.
#Display Top 10 Rows of The Dataset

df2.head(10)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011.0,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011.0,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011.0,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011.0,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011.0,NaN,San Francisco,NaN
5,6,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,118602.00,8601.00,189082.74,NaN,316285.74,316285.74,2011.0,NaN,San Francisco,NaN
6,7,ALSON LEE,"BATTALION CHIEF, (FIRE DEPARTMENT)",92492.01,89062.90,134426.14,NaN,315981.05,315981.05,2011.0,NaN,San Francisco,NaN
7,8,DAVID KUSHNER,DEPUTY DIRECTOR OF INVESTMENTS,256576.96,0.00,51322.50,NaN,307899.46,307899.46,2011.0,NaN,San Francisco,NaN
8,9,MICHAEL MORRIS,"BATTALION CHIEF, (FIRE DEPARTMENT)",176932.64,86362.68,40132.23,NaN,303427.55,303427.55,2011.0,NaN,San Francisco,NaN
9,10,JOANNE HAYES-WHITE,"CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)",285262.00,0.00,17115.73,NaN,302377.73,302377.73,2011.0,NaN,San Francisco,NaN

In [5]:
#Check Last 10 Rows of The Dataset
df2.tail(10)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
49720,49721,Cheryl Wong,IS Administrator 2,84175.04,0.00,0.00,36207.16,84175.04,120382.20,2012.0,NaN,San Francisco,NaN
49721,49722,Lorna Gotera,Patient Care Assistant,63995.00,18277.02,5039.30,33070.74,87311.32,120382.06,2012.0,NaN,San Francisco,NaN
49722,49723,Simon Ma,Transit Operator,62867.26,21012.84,288.50,36213.04,84168.60,120381.64,2012.0,NaN,San Francisco,NaN
49723,49724,Annette Taylor,Senior Management Assistant,84053.71,0.00,623.70,35702.10,84677.41,120379.51,2012.0,NaN,San Francisco,NaN
49724,49725,Evelyn Doria,Licensed Vocational Nurse,68865.60,18210.47,250.00,33053.16,87326.07,120379.23,2012.0,NaN,San Francisco,NaN
49725,49726,Crystal DeFrantz,Emp & Training Spec 4,84086.48,0.00,624.01,35661.88,84710.49,120372.37,2012.0,NaN,San Francisco,NaN
49726,49727,Antoinette Wells,Transit Operator,66714.31,13722.09,1549.20,38368.67,81985.60,120354.27,2012.0,NaN,San Francisco,NaN
49727,49728,Robert Rudy,Stationary Engineer,73814.00,15484.85,7035.40,24019.82,96334.25,120354.07,2012.0,NaN,San Francisco,NaN
49728,49729,Sean Kerrisk,Carpenter,78931.55,3516.76,2193.00,35710.67,84641.31,120351.98,2012.0,NaN,San Francisco,NaN
49729,49730,Rachelle Axel,Senior Management Assistant,8.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
#Find Shape of Our Dataset (Number of Rows And Number of Columns)
df2.shape

(49730, 13)

In [7]:
print("No. of rows",df2.shape[0])

No. of rows 49730

In [8]:
print("No. of columns",df2.shape[1])

No. of columns 13

In [9]:
#Getting Information About Our Dataset Like Total Number Rows, Total Number of Columns, Datatypes of Each Column And Memory Requirement
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49730 entries, 0 to 49729
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Id                49730 non-null  int64
 1   EmployeeName      49730 non-null  object
 2   JobTitle          49730 non-null  object
 3   BasePay           49730 non-null  float64
 4   OvertimePay       49729 non-null  float64
 5   OtherPay          49729 non-null  float64
 6   Benefits          13570 non-null  float64
 7   TotalPay          49729 non-null  float64
 8   TotalPayBenefits  49729 non-null  float64
 9   Year              49729 non-null  float64
 10  Notes             0 non-null      float64
 11  Agency            49729 non-null  object
 12  Status            0 non-null      float64
dtypes: float64(9), int64(1), object(3)
memory usage: 4.9+ MB

In [10]:
#Check Null Values In The Dataset
df2.isnull().sum()

Id                      0
EmployeeName            0
JobTitle                0
BasePay                 0
OvertimePay             1
OtherPay                1
Benefits            36160
TotalPay                1
TotalPayBenefits        1
Year                    1
Notes               49730
Agency                  1
Status              49730
dtype: int64

In [11]:
#Get Overall Statistics About The Dataframe
df2.describe()

,Id,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Status
count,49730.00000,49730.000000,49729.000000,49729.000000,13570.000000,49729.000000,49729.000000,49729.000000,0.0,0.0
mean,24865.50000,75598.465810,6231.691032,4608.484444,40370.376006,86440.161334,97456.389337,2011.272879,NaN,NaN
std,14355.95878,42293.132137,12801.333149,9146.248973,7395.457091,50271.855952,61527.144045,0.445444,NaN,NaN
min,1.00000,0.000000,0.000000,0.000000,189.790000,0.000000,0.000000,2011.000000,NaN,NaN
25%,12433.25000,48472.430000,0.000000,20.330000,36080.740000,52917.430000,52917.430000,2011.000000,NaN,NaN
50%,24865.50000,77251.210000,102.380000,1380.000000,38795.040000,88278.700000,91561.890000,2011.000000,NaN,NaN
75%,37297.75000,105934.660000,6673.030000,5922.060000,43152.130000,119925.870000,140845.590000,2012.000000,NaN,NaN
max,49730.00000,302578.000000,245131.880000,400184.250000,84681.820000,567595.430000,567595.430000,2012.000000,NaN,NaN

In [12]:
df2.describe(include="all")

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
count,49730.00000,49730,49730,49730.000000,49729.000000,49729.000000,13570.000000,49729.000000,49729.000000,49729.000000,0.0,49729,0.0
unique,NaN,47201,1685,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN
top,NaN,KEVIN LEE,TRANSIT OPERATOR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,San Francisco,NaN
freq,NaN,9,2388,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49729,NaN
mean,24865.50000,NaN,NaN,75598.465810,6231.691032,4608.484444,40370.376006,86440.161334,97456.389337,2011.272879,NaN,NaN,NaN
std,14355.95878,NaN,NaN,42293.132137,12801.333149,9146.248973,7395.457091,50271.855952,61527.144045,0.445444,NaN,NaN,NaN
min,1.00000,NaN,NaN,0.000000,0.000000,0.000000,189.790000,0.000000,0.000000,2011.000000,NaN,NaN,NaN
25%,12433.25000,NaN,NaN,48472.430000,0.000000,20.330000,36080.740000,52917.430000,52917.430000,2011.000000,NaN,NaN,NaN
50%,24865.50000,NaN,NaN,77251.210000,102.380000,1380.000000,38795.040000,88278.700000,91561.890000,2011.000000,NaN,NaN,NaN
75%,37297.75000,NaN,NaN,105934.660000,6673.030000,5922.060000,43152.130000,119925.870000,140845.590000,2012.000000,NaN,NaN,NaN
max,49730.00000,NaN,NaN,302578.000000,245131.880000,400184.250000,84681.820000,567595.430000,567595.430000,2012.000000,NaN,NaN,NaN

In [13]:
#Drop ID, Notes, Agency, and Status Columns
df2.drop(["Id","Notes","Agency","Status"],axis=1)

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011.0
1,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011.0
2,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011.0
3,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011.0
4,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011.0
...,...,...,...,...,...,...,...,...,...
49725,Crystal DeFrantz,Emp & Training Spec 4,84086.48,0.00,624.01,35661.88,84710.49,120372.37,2012.0
49726,Antoinette Wells,Transit Operator,66714.31,13722.09,1549.20,38368.67,81985.60,120354.27,2012.0
49727,Robert Rudy,Stationary Engineer,73814.00,15484.85,7035.40,24019.82,96334.25,120354.07,2012.0
49728,Sean Kerrisk,Carpenter,78931.55,3516.76,2193.00,35710.67,84641.31,120351.98,2012.0
49729,Rachelle Axel,Senior Management Assistant,8.00,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
#Find Occurrence of The Employee Names  (Top 5)
df2["EmployeeName"].value_counts().head(5)

KEVIN LEE      9
DAVID WONG     8
MICHAEL LEE    8
RICHARD LEE    8
STANLEY LEE    7
Name: EmployeeName, dtype: int64

In [15]:
#Find The Number of Unique Job Titles
df2["JobTitle"].nunique()

1685

In [16]:
#Total Number of Job Titles Contain Captain
(df2["JobTitle"].str.contains("CAPTAIN",case=False)).count()

49730

In [17]:
len(df2["JobTitle"].str.contains("CAPTAIN"))

49730

In [18]:
# Display All the Employee Names From Fire Department
df2.columns

Index(['Id', 'EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year', 'Notes', 'Agency',
       'Status'],
      dtype='object')

In [19]:
df2[df2["JobTitle"].str.contains("Fire department",case=False)]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011.0,NaN,San Francisco,NaN
6,7,ALSON LEE,"BATTALION CHIEF, (FIRE DEPARTMENT)",92492.01,89062.90,134426.14,NaN,315981.05,315981.05,2011.0,NaN,San Francisco,NaN
8,9,MICHAEL MORRIS,"BATTALION CHIEF, (FIRE DEPARTMENT)",176932.64,86362.68,40132.23,NaN,303427.55,303427.55,2011.0,NaN,San Francisco,NaN
9,10,JOANNE HAYES-WHITE,"CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)",285262.00,0.00,17115.73,NaN,302377.73,302377.73,2011.0,NaN,San Francisco,NaN
10,11,ARTHUR KENNEY,"ASSISTANT CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)",194999.39,71344.88,33149.90,NaN,299494.17,299494.17,2011.0,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5498,5499,VINCENT PEREZ,"LIEUTENANT, FIRE DEPARTMENT",59663.78,13979.51,47704.14,NaN,121347.43,121347.43,2011.0,NaN,San Francisco,NaN
8436,8437,JENSEN RHODES,"LIEUTENANT, FIRE DEPARTMENT",93066.59,1626.13,10703.77,NaN,105396.49,105396.49,2011.0,NaN,San Francisco,NaN
16285,16286,AARON STEVENSON,"ASSISTANT CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)",21948.99,14065.26,37430.72,NaN,73444.97,73444.97,2011.0,NaN,San Francisco,NaN
32623,32624,JAMES BARDEN,"BATTALION CHIEF, (FIRE DEPARTMENT)",0.00,1290.69,5802.68,NaN,7093.37,7093.37,2011.0,NaN,San Francisco,NaN
36162,36163,Joanne Hayes-White,"Chief, Fire Department",296943.01,0.00,17816.59,72047.88,314759.60,386807.48,2012.0,NaN,San Francisco,NaN

In [20]:
len(df2[df2["JobTitle"].str.contains("Fire department",case=False)])

223

In [21]:
df2[df2["JobTitle"].str.contains("Fire department",case=False)]["EmployeeName"]

4           PATRICK GARDNER
6                 ALSON LEE
8            MICHAEL MORRIS
9        JOANNE HAYES-WHITE
10            ARTHUR KENNEY
                ...
5498          VINCENT PEREZ
8436          JENSEN RHODES
16285       AARON STEVENSON
32623          JAMES BARDEN
36162    Joanne Hayes-White
Name: EmployeeName, Length: 223, dtype: object

In [22]:
#Find Minimum, Maximum, and Average BasePay
df2.columns

Index(['Id', 'EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year', 'Notes', 'Agency',
       'Status'],
      dtype='object')

In [23]:
df2["TotalPayBenefits"].describe()

count     49729.000000
mean      97456.389337
std       61527.144045
min           0.000000
25%       52917.430000
50%       91561.890000
75%      140845.590000
max      567595.430000
Name: TotalPayBenefits, dtype: float64

In [24]:
df2["TotalPayBenefits"].max()

567595.43

In [25]:
df2["TotalPayBenefits"].min()

0.0

In [26]:
df2["TotalPayBenefits"].mean()

97456.38933740876

In [27]:
#Replace 'Not Provided' in EmployeeName' Column to NaN
import numpy as np

In [28]:
df2.columns

Index(['Id', 'EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year', 'Notes', 'Agency',
       'Status'],
      dtype='object')

In [29]:
import numpy as np
df2["EmployeeName"].replace("Not provided",np.nan)

0           NATHANIEL FORD
1             GARY JIMENEZ
2           ALBERT PARDINI
3        CHRISTOPHER CHONG
4          PATRICK GARDNER
               ...
49725     Crystal DeFrantz
49726     Antoinette Wells
49727          Robert Rudy
49728         Sean Kerrisk
49729        Rachelle Axel
Name: EmployeeName, Length: 49730, dtype: object

In [30]:
#We can use this also for replacement without import numpy
df2["EmployeeName"].replace(to_replace="Not provided",value="Nan")

0           NATHANIEL FORD
1             GARY JIMENEZ
2           ALBERT PARDINI
3        CHRISTOPHER CHONG
4          PATRICK GARDNER
               ...
49725     Crystal DeFrantz
49726     Antoinette Wells
49727          Robert Rudy
49728         Sean Kerrisk
49729        Rachelle Axel
Name: EmployeeName, Length: 49730, dtype: object

In [33]:
#Find Job Title of ALBERT PARDINI
df2.columns

Index(['Id', 'EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year', 'Notes', 'Agency',
       'Status'],
      dtype='object')

In [41]:
df2[df2["EmployeeName"]=="ALBERT PARDINI"]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011.0,NaN,San Francisco,NaN

In [42]:
df2[df2["EmployeeName"]=="ALBERT PARDINI"]["JobTitle"]

2    CAPTAIN III (POLICE DEPARTMENT)
Name: JobTitle, dtype: object

In [46]:
#How Much ALBERT PARDINI Make (Include Benefits)?
df2[df2["EmployeeName"]=="ALBERT PARDINI"]["TotalPayBenefits"]

2    335279.91
Name: TotalPayBenefits, dtype: float64

In [57]:
#Display Name of The Person Having The Highest BasePa
df2["BasePay"].max()

302578.0

In [58]:
df2[df2["BasePay"].max()==df2["BasePay"]]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
36160,36161,Gregory Suhr,Chief of Police,302578.0,0.0,18974.11,69810.19,321552.11,391362.3,2012.0,NaN,San Francisco,NaN

In [59]:
df2[df2["BasePay"].max()==df2["BasePay"]]["EmployeeName"]

36160    Gregory Suhr
Name: EmployeeName, dtype: object

In [64]:
#Find Average BasePay of All Employee Per Year
df2.groupby("Year").mean()["BasePay"]

<ipython-input-64-6bb0055f8afc>:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df2.groupby("Year").mean()["BasePay"]

Year
2011.0     63595.956517
2012.0    107586.256820
Name: BasePay, dtype: float64

In [66]:
#Find Average BasePay of All Employee Per JobTitle
df2.groupby("JobTitle").mean()["BasePay"]

<ipython-input-66-85b729a9f5bc>:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df2.groupby("JobTitle").mean()["BasePay"]

JobTitle
ACCOUNT CLERK                                     43300.806506
ACCOUNTANT                                        46643.172000
ACCOUNTANT INTERN                                 28732.663958
ACUPUNCTURIST                                     66374.400000
ADMINISTRATIVE ANALYST                            63435.628602
                                                      ...
Wire Rope Cable Maint Sprv                        88634.010000
Worker's Comp Supervisor 1                        98807.242500
X-RAY LABORATORY AIDE                             47664.773077
YOUTH COMMISSION ADVISOR, BOARD OF SUPERVISORS    52609.910000
ZOO CURATOR                                       43148.000000
Name: BasePay, Length: 1685, dtype: float64

In [69]:
# Find Average BasePay of Employee Having Job Title ACCOUNTANT
df2[df2["JobTitle"]=="ACCOUNTANT"]["BasePay"]

19263    65392.01
19324    65225.31
20992    60076.24
25927    42522.30
35285        0.00
Name: BasePay, dtype: float64

In [73]:
#Find Top 5 Most Common Jobs
df2["JobTitle"].value_counts().head(5)

TRANSIT OPERATOR    2388
SPECIAL NURSE       1402
REGISTERED NURSE    1219
Registered Nurse     996
CUSTODIAN            796
Name: JobTitle, dtype: int64